# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
#Solution
import numpy as np
n=np.arange(10,25)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [5]:
# Solution
span=np.arange(1,50,2)
print(span)
print('\nLength of array is: ',len(span))



[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]

Length of array is:  25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [9]:
# Solution
c=np.linspace(4,7,27)
c



array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [12]:
# Solution
matrix=np.round((np.random.uniform(4,size=(5,4))),2)
matrix



array([[2.61, 1.35, 3.04, 3.45],
       [1.09, 2.03, 1.  , 2.98],
       [2.68, 2.38, 3.55, 1.93],
       [3.69, 2.31, 3.5 , 3.68],
       [1.73, 3.67, 2.84, 1.48]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [15]:
# Solution
matrix=np.round((np.random.uniform(5,15,size=(5,5))))
matrix

array([[11.,  6.,  5.,  6., 12.],
       [12.,  5.,  8., 13., 15.],
       [ 7.,  6.,  9., 13., 11.],
       [ 5.,  5.,  7., 13.,  6.],
       [14.,  6., 13.,  7.,  9.]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [31]:
# Solution
oned=np.zeros(20,int)
print('Array of zeroes: ',oned)
oned.dtype


Array of zeroes:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


dtype('int32')

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [34]:
# Solution
twod=np.ones([5,5],dtype='float32')
twod

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [41]:
# Solution
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print('The matrix : \n',mat)
print('\nType :\n',type(mat))
print('\nThe shape is : ',mat.shape)
print('\n DATATYPE :',mat.dtype)

The matrix : 
 [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

Type :
 <class 'numpy.ndarray'>

The shape is :  (5, 5)

 DATATYPE : int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [45]:
# Solution
col=row=int(len(mat)/2)
ar[row,col]

3

#### 10. Print the all the elements of 3rd row of the matrix

In [48]:
# Solution
mat[2:3]

array([[ 5,  7,  3, 76,  3]])

#### 11. Print the all the elements of 4th columns of the matrix

In [52]:
# Solution
mat[:,4]



array([45,  2,  3,  6,  8])

#### 12. Print the 4 corner pixels of the matrix

In [54]:
# Solution
mat[[0,4],:][:,[0,4]]


array([[ 9, 45],
       [23,  8]])

#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [56]:
# Solution 
m1=mat[[0,1],:][:,[2,3]]
print('m1 matrix: ',m1)
m2=mat[[3,4],:][:,[0,1]]
print('m2 matrix:',m2)
m3=mat[[2,3,4],:][:,[2,3,4]]
print('m3 matrix:',m3)

m1 matrix:  [[50 34]
 [34 65]]
m2 matrix: [[ 7  8]
 [23 12]]
m3 matrix: [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [60]:
# Solution
re_m1=m1.reshape(-1,1)
print('new m1:\n',re_m1)
re_m2=m2.reshape(-1,1)
print('new m2 is \n',re_m2)
re_m3=m3.reshape(-1,1)
print('new m3:\n',re_m3)


new m1:
 [[50]
 [34]
 [34]
 [65]]
new m2 is 
 [[ 7]
 [ 8]
 [23]
 [12]]
new m3:
 [[ 3]
 [76]
 [ 3]
 [ 6]
 [54]
 [ 6]
 [ 8]
 [ 5]
 [ 8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [76]:
# Solution
print('Horizontal concatenation:')
horz=np.concatenate((m1,m2),axis=1)
print('\n',horz)
print('\n')
print('Vertical concatenation:')
ver=np.concatenate((m1,m2))
print('\n',ver)

Horizontal concatenation:

 [[50 34  7  8]
 [34 65 23 12]]


Vertical concatenation:

 [[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [69]:
# Solution
print('m1 + m2 : \n',np.add(m1,m2))
print('\nm1 - m2 : \n',np.subtract(m1,m2))
print('\nm1 * m2 : \n',np.multiply(m1,m2))
print('\nm1 / m2 : \n',np.divide(m1,m2))


m1 + m2 : 
 [[57 42]
 [57 77]]

m1 - m2 : 
 [[43 26]
 [11 53]]

m1 * m2 : 
 [[350 272]
 [782 780]]

m1 / m2 : 
 [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [82]:
# Solution
m3_new=np.delete(np.delete(m3,0,0),2,1)
print('',m1+m3_new)

 [[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [83]:
# Solution
me1=np.mean(m1,axis=0)
me2=np.mean(m1,axis=0)
m4=np.concatenate((me1,me2),axis=0)
m4

array([42. , 49.5, 42. , 49.5])

#### 19. Perform the matrix multiplication between m3 and m4

In [90]:
# Solution
m3=m3=mat[[2,3,4],:][:,[2,3,4]].reshape([-1,1])
np.multiply(m3,m4)

array([[ 126. ,  148.5,  126. ,  148.5],
       [3192. , 3762. , 3192. , 3762. ],
       [ 126. ,  148.5,  126. ,  148.5],
       [ 252. ,  297. ,  252. ,  297. ],
       [2268. , 2673. , 2268. , 2673. ],
       [ 252. ,  297. ,  252. ,  297. ],
       [ 336. ,  396. ,  336. ,  396. ],
       [ 210. ,  247.5,  210. ,  247.5],
       [ 336. ,  396. ,  336. ,  396. ]])

#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [113]:
# Solution
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
mean1=mat.max(axis=1)
print('Maximum value of mean',mean1.mean())
mean2=mat.min(axis=1)
print('Minimum value of mean',mean2.mean())
var1=mat.var(axis=1)
std1=mat.std(axis=1)
print('Variance : ',var1)
print('Standard deviation :',std1)


Maximum value of mean 53.6
Minimum value of mean 5.0
Variance :  [214.64 548.24 820.16 357.76  39.76]
Standard deviation : [14.65059726 23.41452541 28.63843571 18.91454467  6.30555311]


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [92]:
# Solution 
run=np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]]).reshape([-1,1])
balls=np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]]).reshape([-1,1])
avg=run.mean(axis=1)
totrun=run.sum(axis=1)
totballs=balls.sum(axis=1) 
strikerate=totrun/totballs
strike_rate=np.sort(strikerate) [::-1]
average=np.sort(avg) [::-1]
print('Average runs:\n',average)
print('\nStrike Rate: ',strike_rate)

Average runs:
 [110. 102.  92.  78.  65.  60.  56.  54.  42.  32.  22.  12.  12.  11.
  10.   8.   6.   3.   2.   1.]

Strike Rate:  [2.07407407 2.         1.42857143 1.35483871 1.2        1.1
 1.09090909 1.08       1.07368421 0.91089109 0.83333333 0.74418605
 0.61111111 0.5        0.45454545 0.40740741 0.4        0.33333333
 0.25       0.14285714]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [96]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
students=np.array(marks>50).sum()
print('Number of students passed : '+str(students))

failed_stud=np.array(marks<=50).sum()
print('\nNumber of students failed : '+str(failed_stud))



Number of students passed : 7

Number of students failed : 3


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [105]:
# Solution
n1=marks[(marks>45) &(marks <49)]+10
print('Mercy mark of students between 45,49 :')
print(n1)
new=marks[(marks>80)&(marks<99)]+5
print('Bonus marks of students with greater than 80: ',new)

Mercy mark of students between 45,49 :
[57 58]
Bonus marks of students with greater than 80:  [ 89  94 103]


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [106]:
# Solution
import time
list3=[]
st=time.time()
l1=list(range(1,60001))
l2=list(range(1,60001))
for i,j in zip(l1,l2):
        list3.append((i**2+8)/j)
print((time.time()-st)*1000,'ms')



424.29471015930176 ms


#### 25. Create a Github account and upload your solution with the short write-up on Numpy

In [ ]:
# Solution
https://github.com/ayruscm/Numpy-Exercise


